version: "3.9"
services:
  ui:
    build:
      context: ../..  # root of the project
      dockerfile: src/deploy/container-ui/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app/src
   

  fastapi-app:
    build:
      context: ../..  # root of the project
      dockerfile: src/deploy/container-backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - CMAKE_ARGS="-DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS"
      - CC=/usr/bin/gcc
      - CXX=/usr/bin/g++
    dns:
     - 8.8.8.8
    
